### ISSUE TITLE
Chat : Leaving a channel is a murder

### ISSUE THREAD

**Issue by Deacllock** [42rave/transcendence#118]
![image](https://github.com/42rave/transcendence/assets/66304704/1ec7c2dc-2aa8-4866-9045-72558e9dc299)
![image](https://github.com/42rave/transcendence/assets/66304704/99e6f023-d5ec-4161-b03b-9a194753b14d)

Issue : When a user quit a channel it deletes the channel for everyone (even people in the channel) no matter if the user is owner or not.

Solution : Check the back: delete the channel only if you are the last person in there. (What about owners?)

**Comment by AdrianWeaver** [comment]
Fixed, PR incoming.
