### ISSUE TITLE
Add a check on socketId (when joining channel)

### ISSUE THREAD

**Issue by riblanc** [42rave/transcendence#60]
When joining a channel, the user can specify a socketId in order to join the room, but in fact there is no control over this socketId to know if the socket belongs to this user and not another.

A simple if statement can be done:
```ts
const socket = this.server.sockets.get(socketId);
if (socket.user.id !== request.user.id)
  throw ForbiddenException("Bouuuuh pas bien >:( Vilain hacker!!!");
```

**Comment by AdrianWeaver** [comment]
This was dealt with in pr #55
