### ISSUE TITLE
Logout user when 401 response

### ISSUE THREAD

**Issue by AdrianWeaver** [42rave/transcendence#67]
If a trusted device is removed for a user (maybe we could add a feature to remove all trusted devices ?!), we need to remove the cookie from the client that is in essence delogged.

So if the authentificationGuard sends a 40x response we need to clear the access_token !

**Comment by riblanc** [comment]
I changed the title for a more accurate one :eyes:

Then, i'd like to clarify a point about this issue.
In fact it's not especially a deal with trusted device, but something more general.

If, for any reason, the webapp think the user is authenticated, but his token (or his device) isn't valid anymore, then the backend could sends a 401 Response.
Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated".
So when the backend returns such a response, the frontend has to disconnect the user and ask him to connect again.
